# Changelog Manager Configuration
# Place this file as .changelog.yaml in your repository root

# Changelog settings (developer-focused CHANGELOG.md)
changelog:
  # Use conventional commits for automatic categorization
  conventional_commits: true
  
  # Include full commit hash in entries
  include_commit_hash: false
  
  # Include short hash (7 chars) in entries
  include_short_hash: true
  
  # Include author attribution (@username)
  include_authors: true
  
  # Include PR/issue numbers
  include_references: true
  
  # Group commits by these strategies (order matters)
  grouping:
    - pull_request      # Group by PR first
    - feature_branch    # Then by feature branch
    - semantic_similarity # Finally by related changes
  
  # Categories to use (Keep a Changelog format)
  categories:
    - Added
    - Changed
    - Deprecated
    - Removed
    - Fixed
    - Security
  
  # Indicators of breaking changes
  breaking_indicators:
    - "BREAKING CHANGE:"
    - "BREAKING:"
    - "!:"              # Conventional commit breaking change
  
  # Files/patterns to ignore
  ignore_patterns:
    - "^docs:"         # Documentation-only commits
    - "^chore\\(deps"  # Dependency updates
    - "^Merge branch"  # Merge commits
    - "^wip:"          # Work in progress

# Release notes settings (user-focused RELEASE_NOTES.md)
release_notes:
  # Target audience
  audience: "end-users"  # Options: "end-users", "developers", "stakeholders"
  
  # Writing tone
  tone: "professional"   # Options: "professional", "casual", "technical"
  
  # Include visual elements (screenshots/gifs)
  include_visuals: false
  
  # Use emoji in headings and bullets
  use_emoji: true
  
  # Emoji mapping for categories
  emoji_map:
    features: "âœ¨"
    improvements: "âš¡"
    fixes: "ðŸ›"
    security: "ðŸ”’"
    breaking: "âš ï¸"
    deprecated: "ðŸ“"
  
  # Maximum entries per category (0 = unlimited)
  max_entries: 0
  
  # Highlight threshold (changes with this many files get highlighted)
  highlight_threshold: 20
  
  # Include "Coming Soon" section
  include_upcoming: true

  # Project context integration (enabled by default)
  project_context_enabled: true

  # Project context sources (priority order: .changelog.yaml > CLAUDE.md > README.md > docs/)
  project_context_sources:
    - "CLAUDE.md"
    - "README.md"
    - "docs/README.md"
    - "docs/**/*.md"

  # Maximum characters per file for context extraction
  project_context_max_length: 5000

  # Cache project context for faster subsequent runs
  project_context_cache_ttl_hours: 24

  # Fallback if no documentation found: "generate_generic_context", "use_defaults", "skip"
  project_context_fallback: "generate_generic_context"

  # Custom instructions (HIGHEST priority - override extracted context)
  emphasis_areas:
    - "Security"
    - "Performance"
    - "User Experience"

  # De-emphasize these in RELEASE_NOTES.md (unless commit indicates user impact)
  de_emphasize:
    - "refactor"
    - "chore"
    - "build"
    - "ci"
    - "deps"
    - "style"
    - "test"

  # Include internal changes in RELEASE_NOTES.md (default: false - they're excluded)
  include_internal_changes: false

  # Keywords indicating user impact (include even if normally de-emphasized)
  user_impact_keywords:
    - "user"
    - "customer"
    - "performance"
    - "faster"
    - "easier"
    - "improves"
    - "fixes"
    - "resolves"

  # Custom terminology mappings (technical term â†’ user-facing term)
  terminology: {}
    # Example:
    # authentication: "sign-in system"
    # API: "developer tools"

  # Special notes for release notes generation
  special_notes: []
    # Example: "Always mention migration guides for breaking changes"

# Historical Replay Configuration (for /changelog-init --replay)
replay:
  # Enable replay mode by default for changelog initialization
  enabled: false

  # Default period grouping strategy
  # Options: "daily", "weekly", "monthly", "quarterly", "annual", "by-release", "auto"
  default_strategy: "auto"

  # Auto-detection thresholds (when strategy is "auto")
  auto_detection:
    # Use release-based strategy if repository has this many or more releases
    min_releases_for_release_strategy: 3

    # Use monthly strategy if project age exceeds this many months
    min_months_for_monthly_strategy: 6

    # Use daily strategy if average commits per day exceeds this threshold
    daily_if_commits_per_day_exceed: 5

    # Use weekly strategy if average commits per week exceeds this threshold
    weekly_if_commits_per_week_exceed: 20

    # Default to quarterly for very long histories (in months)
    long_history_threshold_months: 24

  # Calendar alignment settings
  calendar:
    # Align periods to calendar boundaries
    align_to_calendar: true

    # Week starts on (ISO 8601 standard)
    week_start: "monday"  # Options: "monday", "sunday"

    # Use calendar months (Jan 1-31) vs rolling 30-day periods
    use_calendar_months: true

    # Fiscal year start month (0 = January, 3 = April, etc.)
    fiscal_year_start_month: 0

  # Period boundary handling
  boundaries:
    # How to handle commits on exact boundary dates
    # "inclusive_start": Include in earlier period
    # "exclusive_end": Include in later period
    # "both": Duplicate in both periods with notes
    boundary_handling: "inclusive_start"

    # How to handle unreleased commits (after last complete period)
    # "include": Add to [Unreleased] section
    # "exclude": Omit from changelog
    # "separate_section": Create dedicated section
    unreleased_handling: "include"

  # Period filtering options
  filters:
    # Minimum commits per period to include (periods with fewer commits are skipped)
    min_commits: 1

    # Skip periods containing only merge commits
    skip_merge_only_periods: true

    # Maximum periods to process (0 = unlimited)
    # Useful for testing or limiting analysis scope
    max_periods: 0

    # Start analysis from specific date (YYYY-MM-DD format)
    # null = start from first commit
    start_date: null

    # End analysis at specific date (YYYY-MM-DD format)
    # null = analyze until HEAD
    end_date: null

    # Include only periods matching git tag pattern (regex)
    # null = include all periods
    tag_pattern: null  # Example: "v*", "release-*"

  # Output format preferences
  output:
    # Generate hybrid format (version sections + time periods)
    # true: ## [v2.0.0] - 2024-10-15
    #       ### Week of October 14
    #       ### Week of October 7
    # false: Standard Keep a Changelog format
    hybrid_format: true

    # Include period headers in CHANGELOG.md
    include_period_headers: true

    # Template for period headers
    # Available variables: {period_label}, {start_date}, {end_date}, {commit_count}
    period_header_format: "### {period_label}"

    # Generate separate period-specific release notes
    generate_period_notes: false

    # Include statistics per period
    include_period_stats: true

    # Include navigation/table of contents for long changelogs
    include_navigation: true

    # Apply replay structure to RELEASE_NOTES.md
    # true: Include period summaries in release notes
    # false: Standard consolidated release notes
    replay_in_release_notes: true

  # Performance and execution settings
  performance:
    # Enable parallel processing of periods
    enable_parallel: true

    # Maximum concurrent period analyses
    # Higher values = faster but more API usage
    # Recommended: 3 for balance of speed and cost
    max_concurrent_periods: 3

    # Batch size for commit analysis within each period
    batch_size: 50

    # Enable caching of period analysis results
    enable_cache: true

    # Cache time-to-live in days (0 = never expire)
    cache_ttl_days: 0

    # Cache storage location (relative to repository root)
    cache_location: ".changelog-cache/"

  # Edge case handling
  edge_cases:
    # Minimum commits to avoid "summary mode" for first period
    # First periods with more commits use summarization
    first_period_summary_threshold: 100

    # How to handle periods with multiple version tags
    # "highest": Use highest version number
    # "latest": Use most recent by date
    # "first": Use earliest by date
    multiple_tags_strategy: "highest"

    # How to handle gaps in commit history (months with no activity)
    # "skip": Omit empty periods entirely
    # "mark_as_inactive": Include with "No changes" note
    # "merge_adjacent": Combine with adjacent periods
    gap_handling: "skip"

    # How to handle incomplete final period
    # "include": Add to last completed period
    # "unreleased": Move to [Unreleased] section
    # "separate": Create partial period with note
    incomplete_final_period: "unreleased"

  # Regeneration settings
  regeneration:
    # Allow regenerating specific periods without full replay
    # Example: /changelog-init --replay-period 2024-Q3
    allow_partial_regeneration: true

    # Preserve manual edits when regenerating
    preserve_manual_edits: true

    # Backup existing changelog before regeneration
    create_backup: true

    # Backup file naming pattern
    backup_pattern: "CHANGELOG.{timestamp}.md.backup"

# Version management
versioning:
  # Versioning strategy
  strategy: "semver"  # Options: "semver", "calver", "custom"
  
  # Semantic versioning configuration
  semver:
    # Format: MAJOR.MINOR.PATCH[-PRERELEASE][+BUILD]
    include_v_prefix: true  # Use "v" prefix (v1.0.0 vs 1.0.0)
    
  # Calendar versioning configuration (if strategy: "calver")
  calver:
    format: "YYYY.MM.DD"  # Options: "YYYY.MM.DD", "YYYY.MM", "YY.MM"
    
  # Auto-bump rules (for semver)
  auto_bump:
    breaking: "major"    # Breaking changes trigger major bump
    features: "minor"    # New features trigger minor bump
    fixes: "patch"       # Bug fixes trigger patch bump
    
  # Pre-release tags
  prerelease_tags:
    - alpha
    - beta
    - rc
    - preview
    
  # Files containing version numbers to update
  version_files:
    - path: package.json
      pattern: '"version": "{version}"'
    - path: setup.py
      pattern: 'version="{version}"'
    - path: pyproject.toml
      pattern: 'version = "{version}"'
    - path: VERSION
      pattern: '{version}'
    - path: src/version.py
      pattern: 'VERSION = "{version}"'

# AI analysis settings
ai_analysis:
  # Model for commit analysis
  model: "claude-4-5-sonnet"  # Fast and efficient for code analysis
  
  # Analyze commits with unclear messages
  analyze_unclear: true
  
  # Keywords that trigger AI analysis
  unclear_keywords:
    - "fix"
    - "update"
    - "change"
    - "modify"
    - "stuff"
    - "things"
    - "misc"
    - "various"
  
  # Analyze large diffs for better understanding
  analyze_large_diffs: true
  
  # Threshold for "large" diff (lines changed)
  large_diff_threshold: 100
  
  # Maximum tokens per analysis (cost control)
  max_tokens_per_analysis: 500
  
  # Batch size for parallel processing
  batch_size: 10
  
  # Cache analysis results
  enable_cache: true
  cache_ttl: 30  # Days

# Release configuration
release:
  # Branches allowed for releases
  allowed_branches:
    - main
    - master
    - release/*
    - hotfix/*
  
  # Required checks before release
  pre_release_checks:
    tests_pass: true
    no_uncommitted: true
    changelog_valid: true
    branch_up_to_date: true
  
  # Automatically create these during release
  auto_create:
    git_tag: true
    git_commit: true
    release_branch: false
    github_release: false
  
  # Tag message template
  tag_message_template: "Release {version}"
  
  # Commit message template
  commit_message_template: "chore(release): Prepare v{version}"
  
  # Post-release actions
  post_release:
    - create_unreleased_section
    - update_readme_badge
    - notify_team

# Monorepo configuration (optional)
monorepo:
  enabled: false
  
  # Package directories
  packages:
    - packages/core
    - packages/cli
    - packages/ui
  
  # Version independently
  independent_versioning: false
  
  # Create root changelog
  root_changelog: true
  
  # Include package prefix in entries
  include_package_prefix: true

# Integration settings
integrations:
  # GitHub integration
  github:
    enabled: true  # Auto-enabled if GitHub remote detected and gh CLI available
    create_releases: false
    release_draft: true

    # GitHub matching integration
    matching:
      enabled: true  # Match commits to issues/PRs/projects/milestones
      cache_ttl_hours: 24  # Cache GitHub data for 24 hours
      time_window_days: 14  # Match commits within Â±14 days of artifact activity
      confidence_threshold: 0.85  # Minimum confidence to include a match

      # Artifact types to fetch and match
      fetch:
        issues: true
        pull_requests: true
        projects: true  # GitHub Projects V2
        milestones: true

      # Matching strategies (all enabled by default)
      strategies:
        explicit_reference: true  # Parse #123, fixes #456 from messages
        timestamp_correlation: true  # Match by commit/artifact timestamps
        semantic_similarity: true  # AI-powered semantic matching

      # Composite scoring bonuses
      scoring:
        timestamp_and_semantic_bonus: 0.15  # +15% when both strategies match
        timestamp_and_branch_bonus: 0.10  # +10% when timestamp + PR branch match
        all_strategies_bonus: 0.20  # +20% when 3+ strategies align

      # Semantic matching settings
      semantic:
        min_similarity_score: 0.40  # Minimum AI similarity (0.0-1.0)
        context_length: 2000  # Chars to compare from issue/PR body

    # Display preferences for GitHub references
    references:
      # CHANGELOG.md (technical documentation)
      changelog:
        include_references: true
        format: "detailed"  # Options: "detailed", "inline", "minimal"
        show_issue_refs: true
        show_pr_refs: true
        show_project_refs: true
        show_milestone_refs: false
        show_authors: true

      # RELEASE_NOTES.md (user-facing documentation)
      release_notes:
        include_references: true
        format: "minimal"  # Options: "detailed", "inline", "minimal", "none"
        show_issue_refs: true
        show_pr_refs: false
        show_project_refs: false
        show_milestone_refs: false
        show_authors: false
    
  # GitLab integration
  gitlab:
    enabled: false
    create_releases: false
    
  # Jira integration
  jira:
    enabled: false
    url: "https://company.atlassian.net"
    project_key: "PROJ"
    
  # Slack notifications
  slack:
    enabled: false
    webhook_url: ""
    channel: "#releases"

# Output formatting
output:
  # Date format in changelogs
  date_format: "YYYY-MM-DD"  # ISO 8601
  
  # Line width for wrapping
  line_width: 80
  
  # Indentation
  indent_size: 2
  
  # Include table of contents
  include_toc: true
  
  # Include statistics section
  include_stats: true
  
  # Include contributor list
  include_contributors: true

# Advanced settings
advanced:
  # Parallel processing
  parallel_processing: true
  
  # Number of workers for parallel processing
  workers: 5
  
  # Memory limit per worker (MB)
  memory_limit: 512
  
  # Timeout per analysis (seconds)
  analysis_timeout: 30
  
  # Retry failed analyses
  retry_failed: true
  max_retries: 3
  
  # Verbose output
  verbose: false
  
  # Debug mode
  debug: false

# Hooks (optional)
hooks:
  # Pre-release hook script
  pre_release: ".changelog-hooks/pre-release.sh"
  
  # Post-release hook script
  post_release: ".changelog-hooks/post-release.sh"
  
  # Pre-update hook script
  pre_update: ".changelog-hooks/pre-update.sh"
  
  # Post-update hook script
  post_update: ".changelog-hooks/post-update.sh"

# Custom templates (optional)
templates:
  # Custom changelog entry template
  changelog_entry: "- {description} ({references})"
  
  # Custom release notes feature template
  release_feature: "### {emoji} {title}\n{description}\n"
  
  # Custom version header template
  version_header: "## [{version}] - {date}"
